name: Custom Permissions
type: module
description: Allows additional permissions to be created and managed through an administration form.
# core: 8.x
configure: custom_perms_select_list_form
package: Permissions
features: true

# Information added by Drupal.org packaging script on 2019-07-10
version: '8.x-1.2'
core: '8.x'
project: 'config_perms'
datestamp: 1562775795
